USE QuanLyBanHang;
CREATE USER [thuvan2002] FOR LOGIN [thuvan2002];
GRANT ALL PRIVILEGES TO [thuvan2002];
CREATE USER [TruongLV] FOR LOGIN [thuvan2002];
CREATE ROLE [PhongKT];
EXEC sp_addrolemember 'PhongKT', 'TruongLV';
CREATE USER [AnLV] FOR LOGIN [thuvan2002];
GRANT SELECT, INSERT, UPDATE, DELETE ON [dbo].[SanPham] TO [TruongLV];
GRANT SELECT, INSERT, UPDATE, DELETE ON [dbo].[Hangsx] TO [TruongLV];
GRANT SELECT, INSERT, UPDATE, DELETE ON [dbo].[Nhap] TO [TruongLV];
GRANT SELECT, INSERT, UPDATE, DELETE ON [dbo].[Xuat] TO [TruongLV];
GRANT SELECT, INSERT, UPDATE, DELETE ON [dbo].[Nhanvien] TO [TruongLV];
GRANT SELECT, INSERT,UPDATE, DELETE ON [dbo].[SanPham] TO [AnLV];
GRANT SELECT, INSERT,UPDATE, DELETE ON [dbo].[Hangsx] TO [AnLV];
GRANT SELECT, INSERT,UPDATE, DELETE ON [dbo].[Nhap] TO [AnLV];
GRANT SELECT, INSERT,UPDATE, DELETE ON [dbo].[Xuat] TO [AnLV];
GRANT SELECT, INSERT,UPDATE, DELETE ON [dbo].[Nhanvien] TO [AnLV];

GRANT SELECT, EXECUTE ON [dbo].[view1] TO [TruongLV];
GRANT SELECT, EXECUTE ON [dbo].[view2] TO [TruongLV];
GRANT SELECT, EXECUTE ON [dbo].[view3] TO [TruongLV];
GRANT SELECT, EXECUTE ON [dbo].[view1] TO [AnLV];
GRANT SELECT, EXECUTE ON [dbo].[view2] TO [AnLV];
GRANT SELECT, EXECUTE ON [dbo].[view3] TO [AnLV];

USE QuanLyBanHang;
GRANT CREATE TABLE TO PhongKT;
USE QuanLyBanHang;
GRANT VIEW DATABASE TO AnLV;
GRANT INSERT ON [dbo].[PhongMay] TO AnLV;
-- Cho phép AnLV cấp lại quyền
GRANT WITH GRANT OPTION TO AnLV;